lib/sidekiq/scheduler.rb, sidekiq-scheduler.gemspec, test/lib/sidekiq/scheduler_test.rb
I want to pass in some `:lockfile` options to the scheduler. This allows for any options to be set.
As part of the PR, I also updated to rufus-scheduler 3.0+, which has better options other than subclassing Rufus::Scheduler to add different locking semantics.
=> Can pass options to Rufus::Scheduler.new

README.md, lib/sidekiq-scheduler/web.rb, sidekiq-scheduler.gemspec, test/lib/sidekiq/web_test.rb, web/views/recurring_jobs.erb
This adds a "Recurring Jobs" tab to the Sidekiq Web UI nav bar that links to a page with a table containing the current sidekiq-scheduler job schedule.
Inspired by resque-scheduler's resque-web UI integration.
=> Basic Sidekiq Web UI integration

README.md
Rufus expects single characters for intervals, as in `1h`.
If we use `1hr`, Rufus seems to still accept it via a `DateTime.parse` fallback. No idea how `DateTime.parse('1hr')` is interpreted, but it gives a different result.
=> Fix "every" syntax example

lib/sidekiq/scheduler.rb, test/lib/sidekiq/scheduler_test.rb
Rufus scheduler allows the scheduling of jobs to occur one at a specific time such as in the case of an auction that is ending. This pull request adds the specific time methods "at" and "in" as allowable options for sidekiq scheduler.
=> allow the use of rufus scheduler methods [at, in]

index.html
Update the documentation page links to go to rubydoc instead of github
and updated the example of the instalation to reflect the last version
change.
=> Update documentation page

lib/sidekiq-scheduler/schedule.rb, test/schedule_test.rb
Hi there,
I've been using sidekiq sheduler with Rails and I found it bit weird that when I remove a job from my yml file it doesn't get removed and you can still see it in web interface as well.
This fixes it. Let me know what you think!
=> Remove old jobs when assigning schedule

lib/sidekiq/scheduler.rb
I was seeing a lot of this in my sidekiq logs:
```
NameError: uninitialized constant ActiveJob::Enqueuing
```
In a Rails, `ActiveJob` is defined even if `ActiveJob::Enqueuing` is not. `ActiveJob::Enqueuing` is only defined if you actually have a class that subclasses `ActiveJob::Base`. This just makes the `defined?` check more explicit.
=> Fix ActiveJob check

lib/sidekiq-scheduler/web.rb, sidekiq-scheduler.gemspec, web/locales/cs.yml, web/locales/en.yml, web/views/recurring_jobs.erb
Views is possible to localise to foreign languages.
Removed `tilt` gem because of colision with dependencies of gem `sass` in Rails 4 app. Gem looks like unused in `sidekiq-scheduler`.
=> Localization added

lib/sidekiq/scheduler.rb, spec/sidekiq/scheduler_spec.rb, spec/spec_helper.rb, spec/support/faker/job_configurations.rb
Ignore job enqueueing if it has already been enqueued for the same timestamp. 
This solves the problem when multiple sidekiq instances having cron jobs are running.
Issue: #88
=> Prevent enqueueing of duplicated  `cron` and `at` job instances

lib/sidekiq-scheduler/schedule.rb, spec/sidekiq-scheduler/schedule_spec.rb
This change is related to https://github.com/moove-it/sidekiq-scheduler/issues/102
=> Fix bug when job key is a symbol and sidekiq runs twice

lib/sidekiq-scheduler/job_presenter.rb, lib/sidekiq-scheduler/web.rb
Sidekiq 4.2.0 migrated  its web app from Sinatra to a plain Rack app, so some
tweaks are needed to support both approaches.
=> Change web ui to be compatible with Sidekiq 4.2.0

lib/sidekiq-scheduler/web.rb
Clicking the ‘Enqueue Now’ button redirects to ‘/recurring-jobs’ rather
than `{sidekiq-route-namespace}/recurring-jobs’. This follows the
pattern in Sidekiq’s own classes to achieve correct routing
=> Follow sidekiq redirect pattern for 'Enqueue Now' button

lib/sidekiq-scheduler/schedule.rb, lib/sidekiq/scheduler.rb, sidekiq-scheduler.gemspec, spec/sidekiq-scheduler/manager_spec.rb
referencing [issue #135](https://github.com/moove-it/sidekiq-scheduler/issues/135)
This gem is just the hash ext from active support and nothing else.
It adds the least amount of 3rd party code, and does it nicely.
The one test was modified cause it was basically pushing a new key to the options hash rather than replacing the existing key. This is one of those problems with adding a symbol key to a hash with string keys. But with hashwithindifferent access, that problem goes away cause the keys are treated as if they were the same.
This also allows the yml configs to be symbols or strings.
=> add hash with indifferent access

lib/sidekiq-scheduler/job_presenter.rb
Use `||=` as Ruby 1.9 doesn't provide Object#Hash method.
=> Use `hash ||= {}` instead of #Hash

lib/sidekiq-scheduler.rb, lib/sidekiq-scheduler/manager.rb, lib/sidekiq-scheduler/schedule.rb, spec/sidekiq-scheduler/manager_spec.rb, spec/sidekiq-scheduler/schedule_spec.rb
On startup sidekiq hook, set the schedule if it was not previously set,
following the same mechanism as other configuration flags.
=> Set schedule if it was not previously set

sidekiq-scheduler.gemspec
Firstly thanks for your work on this project!
We're starting the process of moving from resque to sidekiq and will be running the two side-by-side while we complete the transition.
resque-scheduler has a rufus-scheduler dependency on `~> 3.2`  while sidekiq-scheduler currently has `~> 3.1.8`. Would you be happy to bump or relax the version constraints?
https://github.com/resque/resque-scheduler/blob/master/resque-scheduler.gemspec#L59
https://github.com/jmettraux/rufus-scheduler/compare/v3.1.8...v3.2.0?expand=1
=> change min rufus-scheduler dep to ~> 3.2

lib/sidekiq-scheduler/schedule.rb, spec/sidekiq-scheduler/manager_spec.rb, spec/sidekiq-scheduler/schedule_spec.rb, spec/support/workers/email_sender.rb
Fixes https://github.com/moove-it/sidekiq-scheduler/issues/157
This change updates the `SidekiqScheduler::Schedule#schedule=` to
infer queue name from the worker. It supports both sidekiq workers
and active jobs by checking for `sidekiq_options` and a `queue_name`.
Note: This change does not update the `set_schedule` method to infer
the queue name but could be updated to handle this case if required.
=> Infer queue name when loading schedule

lib/sidekiq-scheduler/schedule.rb
We send `hash` as param into `set_schedule`, not json (string). In this case `JSON(hash)` raised exception (`JSON::ParserError: lexical error: invalid char in json text.`) and we do not need parse this arg.
=> Fix error JSON::ParserError: lexical error: invalid char in json text on schedule loading

lib/sidekiq-scheduler/rufus_utils.rb, lib/sidekiq/scheduler.rb, spec/sidekiq-scheduler/rufus_utils_spec.rb, spec/sidekiq/scheduler_spec.rb, spec/spec_helper.rb
Display right 'next time' values in Web UI
When options in form of array were passed to the schedule config, 'next time' column
was not being updated.
Schedule configuration sample causing the bug:
```yaml
:schedule:
hello_world:
every: ['30s', first_in: '120s']
class: HelloWorld
```
=> Fix 'next time' when schedule includes options

lib/sidekiq-scheduler/manager.rb, spec/sidekiq-scheduler/manager_spec.rb
This change updates the manager to only set the schedule when
the `enabled` options is `true`. This means that we wont update 
the schedule in Redis when the config passes `enabled` as `false`.
The use case for this was running two processes with different
config options eg.
`bundle exec sidekiq -C config/sidekiq.yml`
`bundle exec sidekiq -C config/sidekiq_schedule.yml`
The `sidekiq_schedule.yml` contains a collection of scheduled
jobs and the `sidekiq.yml` does not contain any scheduled jobs.
What we were seeing was that depending on which is last to run
the `Sidekiq.get_schedule` (from Redis) could either contain the
schedule or return an empty hash.
=> Don't set schedule when not enabled

README.md, lib/sidekiq/scheduler.rb, spec/sidekiq/scheduler_spec.rb
Schedules support now a configuration to pass
a schedule metadata hash as the last argument to the
worker method.
=> Add ability to pass metadata to worker method

lib/sidekiq-scheduler/schedule.rb, lib/sidekiq/scheduler.rb, spec/sidekiq-scheduler/schedule_spec.rb, spec/sidekiq/scheduler_spec.rb
As we discussed in issue #191 , `spop` may lead to unexpected results under distributed scene.
In this PR, I use `Sorted-Set` instead of `Set` to store schedules_changed info. It works like the db migration of Rails.
Notice, This RP will lead a break change:
If a schedules_change has been added before sidekiq server client starts up, the schedules_change will be ignored by the new instance of sidekiq server. Because the member of `schedules_changed` can only be update (its score) and never be deleted, we can't judge which is outdated or pre-added.
=> Use Sorted-Set instead of Set to store 'schedules_changed' in redis

lib/sidekiq-scheduler/schedule.rb, lib/sidekiq-scheduler/web.rb, spec/sidekiq-scheduler/schedule_spec.rb, spec/sidekiq-scheduler/web_spec.rb
Schedule was being fetched only from Redis during startup, so when no data was present in Redis the
schedule will become empty.
The bug was introduced while solving another issue related to the schedule not loaded in the Web UI
process.
Fixed both issues by not fetching from Redis during startup, and loading schedule from Redis at the
Web UI 'toggle' route.
=> Fix non-loading schedule issue

lib/sidekiq-scheduler/schedule.rb, lib/sidekiq/scheduler.rb, spec/sidekiq-scheduler/schedule_spec.rb, spec/sidekiq/scheduler_spec.rb
Asking for an ActiveJob's queue gets back the queue name including a prefix in case is set with
`config.active_job.queue_name_prefix`, and then setting that queue name explicitly while invoking
the job will turn to a duplicate prefix.
Changed to only set the queue name when one is configured via sidekiq.yml
=> Don't explicitly set queue name for ActiveJobs

README.md, lib/sidekiq-scheduler.rb, lib/sidekiq-scheduler/manager.rb, lib/sidekiq/scheduler.rb, spec/sidekiq-scheduler/manager_spec.rb, spec/sidekiq/scheduler_spec.rb
In some situations it doesn't make sense for a queue, which is
updated very rarely, to continually parse the scheduled queue
for new changes.
=> Support :dynamic_every option (default 5s) for :dynamic

sidekiq-scheduler.gemspec
The description on rubygems says "queueinga jobs"...doubt that was the intention.
=> Fix typo in gemspec

README.md
Describe non-normal conditios under which `cron` and `at` jobs could be pushed more than once when
runnning on multiple hosts.
=> Describe non-normal conditios against `cron`, and `at` only-once run

.travis.yml
CI against Ruby 2.3/2.4
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/
=> CI against Ruby 2.3/2.4

README.md
Spent some time tracking down this error and thought a docs update would be helpful:
```
{ 70352380284820 rufus-scheduler intercepted an error:
70352380284820   job:
70352380284820     Rufus::Scheduler::EveryJob "10s" {:first_in=>"1s", :job=>true, :tags=>["example_job"]}
70352380284820   error:
70352380284820     70352380284820
70352380284820     Timeout::Error
70352380284820     Waited 5 sec
70352380284820       /Users/zachwalton/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:86:in `block (2 levels) in pop'
70352380284820       /Users/zachwalton/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `loop'
70352380284820 …
```
=> Add note for connection pool configuration

lib/sidekiq-scheduler/scheduler.rb, spec/sidekiq-scheduler/scheduler_spec.rb
Pass-in :stop option to Rufus::Scheduler#stop in order to avoid
leaking of worker threads.
Also:
- Provide a stop option to be passeod to rufus-scheduler
=> Wait for rufus-scheduler threads to stop

lib/sidekiq-scheduler/job_presenter.rb, spec/sidekiq-scheduler/job_presenter_spec.rb
Sort schedule jobs by name. Closes https://github.com/moove-it/sidekiq-scheduler/issues/258.
=> Sort jobs by name on the web UI

spec/sidekiq-scheduler/web_spec.rb
Those specs are were failing due to a error in mock_redis pipelined
implementation. In mock_redis implementation, array replies are
being flatten and contactenated with other array replies within
the same pipeline, while they shouldn't be contactenated.
=> Mark web specs related to sidekiq stats as pending

lib/sidekiq-scheduler/redis_manager.rb, spec/support/store.rb
With redis 4.2.5 I get deprecated text at startup
```
Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/usr/local/rvm/gems/ruby-2.6.3/gems/sidekiq-scheduler-3.0.1/lib/sidekiq-scheduler/redis_manager.rb:99:in `block in schedule_exist?')
```
Method `exists?` was added recently and most likely will not be available to everyone(https://github.com/redis/redis-rb/blame/master/lib/redis.rb#L601)
=> fix redis exists deprecation warning

lib/sidekiq-scheduler/scheduler.rb
Requiring this gem causes "circular require" warning, e.g.
```
$ ruby -rsidekiq-scheduler -wep
...
.../rubygems/core_ext/kernel_require.rb:94: warning: .../rubygems/core_ext/kernel_require.rb:94: warning: loading in progress, circular require considered harmful - .../gems/sidekiq-scheduler-3.0.1/lib/sidekiq-scheduler/scheduler.rb
from .../rubygems/core_ext/kernel_require.rb:147:in  `require'
from .../rubygems/core_ext/kernel_require.rb:158:in  `rescue in require'
from .../rubygems/core_ext/kernel_require.rb:158:in  `require'
from .../gems/sidekiq-scheduler-3.0.1/lib/sidekiq-scheduler.rb:4:in  `<top (required)>'
from .../gems/sidekiq-scheduler-3.0.1/lib/sidekiq-scheduler.rb:4:in  `require_relative'
from .../gems/sidekiq-scheduler-3.0.1/lib/sidekiq/scheduler.rb:1:in  `<top (required)>'
from …
```
=> Eliminate circular require: scheduler.rb <=> manager.rb

.travis.yml, spec/sidekiq-scheduler/web_spec.rb, web/views/recurring_jobs.erb
Use ERB::Util.url_encode instead of deprecated URI.escape (#333)
Add more rubies to test matrix
=> Add support for Ruby 3.0

README.md
It appears that rufus-scheduler version 3.3.3 [uses the Rails timezone](https://github.com/jmettraux/rufus-scheduler/commit/dc9e9df051b2d9f5379f3cd5c703f078b35b8e3a) if Rails is detected. [This commit](https://github.com/moove-it/sidekiq-scheduler/commit/4b7eb813c67794503f8e1586f937be525d57e1df) bumps the version of rufus-scheduler, allowing it to upgrade to 3.x, which includes the change.
This change modifies the README regarding cron syntax, to indicate that the current version of sidekiq_scheduler does use the Rails timezone when parsing cron statements.
Fixes #309
=> Update README to reflect reading Rails timezone

Gemfile
This PR uses https to talk to rubygems.org for finding gems in development/CI.
=> Gemfile: Refer to https for rubygems.org

lib/sidekiq-scheduler/manager.rb
I was looking through the source here to find a way to reset my state without digging into Redis, and happened up the `reset` method - which, as of https://github.com/moove-it/sidekiq-scheduler/commit/70de80cbc6a1bc675bf4e741b8ce2169635059b1, points to a method that no longer exists.
I just removed it in case anyone else happened to be looking for similar functionality. Looks like only `start`/`stop` are leveraged in the Sidekiq startup hook.
=> Remove defunct reset method

README.md
Fixes #154 (sort of)
This adds important information about job not being enqueued when sidekiq worker is down for any reason at job's scheduled time.
=> Add notes about enqueueing during restart/downtime to readme [ci skip]

README.md
Hello 🙃
I had a hard time understanding which formats for specifying periodic tasks are available. I even had to use a step debugger to get to the actual parsing code.
Here I submit my findings. Hope it will be useful to other users of this library.
Currently the README only mentions one-letter time durations. It looked like a step back from ActiveSupport-enabled durations we had in our Clockwork configuration, like `every(15.minutes)`. That prompted my little research.
Maybe the description can be improved further. Let me know 🙂
=> Add more format examples to README

lib/sidekiq-scheduler/redis_manager.rb, spec/support/store.rb
Reverts moove-it/sidekiq-scheduler#335
Ref: https://github.com/moove-it/sidekiq-scheduler/issues/345
=> Revert "fix redis exists deprecation warning"

lib/sidekiq-scheduler/redis_manager.rb, spec/support/store.rb
Follow-up of https://github.com/moove-it/sidekiq-scheduler/pull/346
When that PR gets merged we need to add support for redis-rb >= 4.3 which will return an integer value for `exists` while prior versions return a boolean value.
Fixing the warning described in original PR https://github.com/moove-it/sidekiq-scheduler/pull/335 will be made in a future PR and will be included only in sidekiq-scheduler v4 as described here https://github.com/moove-it/sidekiq-scheduler/issues/345#issuecomment-881971975
=> Add support for redis-rb >= 4.3

lib/sidekiq-scheduler/extensions/web.rb
Commit 07b9380afc8e037789fcb02c3f7db9a8c779a0dd moved the styles to 
a separate file and mount like the rest of the Sidekiq assets.
It looks like the CSS file does not have its path properly set up.
The CSS path has been adjusted so that it loads properly now.
Before:
After:
Fixes: #352
=> Fix CSS file path in web UI.

web/assets/stylesheets/recurring_jobs.css
The CSS that would run for light-mode users is identical to dark mode's styles.
This adjusts the default styles to at least match closer to the rest of Sidekiq's UI for the default theme (values "borrowed" from Sidekiq's CSS file).
=> Fix CSS for light-mode users

lib/sidekiq-scheduler/version.rb
This version includes:
- Docs improvements
- UI improvement switching from a table to list groups
- Use POST requests to prevent CSRF
- Brings back redis deprecation warning which will only be fixed in sidekiq-scheduler v4 (see https://github.com/moove-it/sidekiq-scheduler/issues/345)
- Add support for redis-rb >= 4.3
=> Bump version to v3.1.1

lib/sidekiq-scheduler/redis_manager.rb
Context: https://github.com/redis/redis-rb/pull/1059
The following is deprecated
```ruby
redis.pipelined do
redis.get(key)
end
```
And should be rewritten as:
```ruby
redis.pipelined do |pipeline|
pipeline.get(key)
end
```
Functionally it makes no difference.
=> Fix deprecated uses of `Redis#pipelined`

lib/sidekiq-scheduler/schedule.rb, lib/sidekiq-scheduler/scheduler.rb, lib/sidekiq-scheduler/utils.rb, spec/sidekiq-scheduler/schedule_spec.rb, spec/sidekiq-scheduler/utils_spec.rb
For https://github.com/moove-it/sidekiq-scheduler/issues/303
=> fix: prevent sidekiq_options from overriding ActiveJob queue settings

web/assets/stylesheets/recurring_jobs.css, web/views/recurring_jobs.erb
This change adds a new CSS class to make disabled jobs more easily identifiable.
This PR resolves this issue: https://github.com/moove-it/sidekiq-scheduler/issues/368
=> Highlight disabled jobs

CHANGELOG.md, lib/sidekiq-scheduler/redis_manager.rb, sidekiq-scheduler.gemspec, spec/sidekiq-scheduler/redis_manager_spec.rb, spec/support/store.rb
- Fixes redis `exists` deprecation warning 
- Requires redis 4.2
Closes #345
=> Require redis 4.2 and fix  deprecation warning

lib/sidekiq-scheduler/scheduler.rb, sidekiq-scheduler.gemspec
They seem to be not in use, thwait has been introduced in https://github.com/moove-it/sidekiq-scheduler/pull/11 and since ruby 2.7 its not bundled with ruby anymore https://github.com/moove-it/sidekiq-scheduler/pull/299, but I can't see sidekiq-scheduler or any dependency of sidekiq-scheduler using it.
I guess these dependencies were added to prevent ruby dependency errors since 2.7 they are not bundled with it, not sure if we are safe to remove them. It will require some tests from the community, tests at least don't fail.
Closes #365
=> Remove thwait and e2mmap as dependencies

README.md, lib/sidekiq-scheduler/scheduler.rb, spec/sidekiq-scheduler/scheduler_spec.rb
This ensures that `rufus_scheduler_options` is read during boot and
`sidekiq-scheduler` instance (that also instantiates rufus scheduler)
is initialized with any custom options passed into `rufus_scheduler_options`.
Doing it this way allows us to not set the `rufus_scheduler_options`, manually
during application runtime (like below), which doesn't take into effect, due to the
memoization of `@rufus_scheduler`.
```ruby
SidekiqScheduler::Scheduler.instance.rufus_scheduler_options = { max_work_threads: 5 }
```
More about the issue here: https://github.com/moove-it/sidekiq-scheduler/issues/374
Fixes: https://github.com/moove-it/sidekiq-scheduler/issues/374
=> Set rufus_scheduler_options via sidekiq.yml file as configuration option

lib/sidekiq-scheduler/manager.rb, lib/sidekiq-scheduler/scheduler.rb, spec/support/initialization/logs.rb
=> Remove Sidekiq::Util

lib/sidekiq-scheduler.rb, lib/sidekiq-scheduler/scheduler.rb
Closes #384 
Sidekiq 6.5 and later changed how config options work.
```ruby
config.options[:x] = 1
config.options[:y] # => 2
config[:x] = 1
config[:y] # => 2
```
The existing functionality works, but now throws a deprication warning and will most likely be removed for Sidekiq 7. There is also no non-depricated way to access the config hash.
To maintain compatability with older Sidekiq versions, a `SIDEKIQ_GTE_6_5_0` has been added which is `true` if `Sidekiq::VERSION` is 6.5 or later. This constant is then used to determine now to pull the Sidekiq config hash and set configuration options where applicable.
This should allow the gem to maintain compatability with Sidekiq < 6.5
=> Remove config get/set depication warning due to Sidekiq 6.5+

lib/sidekiq-scheduler/scheduler.rb
Rufus used `jobs` method instead of `all_jobs`
https://github.com/jmettraux/rufus-scheduler/blob/3fe5a02b4ceae7901228010a0b58e62a3be0e456/lib/rufus/scheduler.rb#L277
=> Fix undefined method error

.github/workflows/ci.yml, Gemfile, lib/sidekiq-scheduler/redis_manager.rb, lib/sidekiq-scheduler/utils.rb, sidekiq-scheduler.gemspec, spec/sidekiq-scheduler/redis_manager_spec.rb, spec/sidekiq-scheduler/scheduler_spec.rb, spec/support/initialization/redis.rb
Fix: https://github.com/redis/redis-rb/issues/1143
- Remove `redis_mock` as it was hiding several bugs
- Explicitly cast time types to string, as redis-rb 5.0 no longer does it implicitly
=> Redis 5.0 compatibility

lib/sidekiq-scheduler/scheduler.rb, spec/sidekiq-scheduler/scheduler_spec.rb
- update `scheduled_at` metadata to string key, hash rocket syntax
- update spec to expect string key, hash rocket syntax
- fixes issue #402
=> Fix metadata for Sidekiq `strict_args!`

README.md, lib/sidekiq-scheduler/redis_manager.rb, spec/sidekiq-scheduler/redis_manager_spec.rb, spec/sidekiq-scheduler/scheduler_spec.rb, spec/support/store.rb
Implements #400
Adds the ability to set a `key_prefix` which will be prepended to all Redis keys. This allows multiple applications to keep their schedules in the same Redis database without clobbering each other.
This change does not affect the runtime of the RSpec suite, but allows for the use case mentioned. Doing the first two commits without the last one would allow for monkey patches, but if we could do the whole thing that would be great.
=> Allow for multiple applications to share a Redis DB

lib/sidekiq-scheduler/schedule.rb, lib/sidekiq-scheduler/utils.rb
Resolves: #407
Initially, I've thought about adding a [managed string inflector](https://github.com/dry-rb/dry-inflector/blob/main/lib/dry/inflector.rb#L88) as a dependency, but there is no need for that just to use this single method.
Instead, I've replaced the with the to avoid additional dependencies.
=> Fix the constantize method

.github/workflows/ci.yml, Gemfile, sidekiq-scheduler.gemspec, spec/sidekiq-scheduler/scheduler_spec.rb
Based on the discussion we had here https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/410
I also fixed some broken specs for Ruby 3/3.1 that were expecting keyword arguments while they actually should expect a hash, which is what we push to sidekiq [here](https://github.com/sidekiq-scheduler/sidekiq-scheduler/blob/master/lib/sidekiq-scheduler/utils.rb#L86).
=> Drop support for EOL Rubies & Sidekiq

.github/workflows/ci.yml, lib/sidekiq-scheduler.rb, lib/sidekiq-scheduler/manager.rb, lib/sidekiq-scheduler/redis_manager.rb, lib/sidekiq-scheduler/scheduler.rb, sidekiq-scheduler.gemspec, spec/sidekiq-scheduler/scheduler_spec.rb, spec/spec_helper.rb, spec/support/sidekiq.rb, spec/support/store.rb
Closes #409 
- Updated the sidekiq dependency in the gemspec.
- Changed the redis gem to be a development dependency.
- Added `SIDEKIQ_GTE_7_0_0` for version checks.
- Implemented changes needed to get sidekiq 7 playing nice using the new constant to fork logic.
I used a near vanilla Rails app with some simple jobs to verify sidekiq boots and scheduled jobs do enqueue and execute.
=> [WIP] Allow Sidekiq 7 to work with the gem

lib/sidekiq-scheduler/manager.rb, sidekiq-scheduler.gemspec
Sidekiq 7.0 depends on redis-client by default, and earlier versions depend on redis.
=> Drop explicit redis dependency

lib/sidekiq-scheduler/manager.rb, lib/sidekiq-scheduler/sidekiq_adapter.rb
Fixes #424
I noticed two instances of `.present?` in 5.0.0 as compared to 4.0.3, and they were preventing me from using 5.0.0 in my non-Rails app. I've changed them back to base Ruby
=> Replace calls to .present?

lib/sidekiq-scheduler/extensions/web.rb
Using rack < 3.0.0 requires all response header keys to be lowercase: https://github.com/rack/rack/commit/472e12f5b6505cc2fdd3b5e529b616b3a2d5fbf8
fixes #431
=> Fix "uppercase character in header name: Cache-Control"

lib/sidekiq-scheduler/redis_manager.rb, lib/sidekiq-scheduler/sidekiq_adapter.rb, spec/support/store.rb
Closes #436 
Sidekiq 7.1 now warns on deprecated Redis commands. `zrangebyscore` is currently used by the gem which is depicated in Redis 6.2 which is the minimum required Redis version for current Sidekiq.
Since we most likely are supporting the latest 7.x of Sidekiq, I reused the "GTE 7.0" check and redirected calls to `zrangebyscore` to use the Sidekiq Adaptor class.
The difference in commands is based off of the changes to Sidekiq when it swapped out the depricated call: https://github.com/sidekiq/sidekiq/commit/1aca434e5cd830cbd0020f1f82ef3a3cb6b2d477#diff-25f829140be25a886134933b537d356dddb12234ca85319e50b381f9edb6b74dR686
=> Don't use depicated Redis commands

README.md
=> Fix a typo in REAMDE

lib/sidekiq-scheduler/extensions/web.rb
As mentioned in https://github.com/sidekiq/sidekiq/issues/5936 the public cache control could leak information when used with CloudFront or other CDNs. It was decided to change the cache setting in Sidekiq web's static assets to private.
This changes the gem's cache-control settings to match the recently released Sidekiq's.
=> Change cache-control to private

README.md
Sidekiq::Worker has been renamed as Sidekiq::Job. See;
* Sidekiq::Job added as an alias in v6.3: https://github.com/sidekiq/sidekiq/blob/main/Changes.md#630
* Sidekiq::Worker replaced with Sidekiq::Job and Sidekiq::Worker retained as an alias in v6.4: https://github.com/sidekiq/sidekiq/blob/main/Changes.md#640
This PR adds a note to the README file to reflect this. The example still uses the old, deprecated version as this will reliably work with all supported versions of Sidekiq.
Fixes #456
=> Add note about Sidekiq::Job

sidekiq-scheduler.gemspec
Hi team. Thanks for this fantastic work!
I will adopt this gem in an internal project here at meilisearch, but we use tilt internally in a newer version. 
Since I ran the test suite with the new version and it didn't break anything, I guess it wouldn't hurt to increase the compatibility range in the scheduler.
So this PR increases the compatibility range to accept any tilt version less than 3.
=> Update tilt dependency (or at least increase compatibility)

spec/support/initialization/redis.rb
The API of Redis commands via Sidekiq was changed at Sidekiq 7.2. This PR fixes to use the new style.
Ref: https://github.com/sidekiq/sidekiq/issues/6083、 https://github.com/sidekiq/sidekiq/commit/3b8a3c3ea29b63b21e01010f630c936d25265712
=> Fix broken CI against Sidekiq 7.2

.github/workflows/ci.yml
This PR just adds Ruby 3.3 to the CI matrix.
=> CI against Ruby 3.3

lib/sidekiq-scheduler/redis_manager.rb
This is another change that I think helped eliminate the multi job issue in addition to #463.
From the Redis [docs](https://redis.io/docs/interact/transactions/)
> All the commands in a transaction are serialized and executed sequentially. A request sent by another client will never be served in the middle of the execution of a Redis Transaction. This guarantees that the commands are executed as a single isolated operation.
The `multi` block form also pipelines the commands so this is just making the command a transaction.
=> Use Redis MULTI command

lib/sidekiq-scheduler/scheduler.rb, spec/sidekiq-scheduler/scheduler_spec.rb
Sidekiq-scheduler allows to schedule jobs using different schedule types. One of the schedule types is `at`, that pushes jobs only once and schedules it in a single point in time. Defining a job in `sidekiq.yml` with an `at` schedule type and a date in the past resulted in an error and prevented Sidekiq from starting:
```
11:36:07 sidekiq.1 | 2024-05-01T09:36:07.190Z pid=515927 tid=axvj INFO: Scheduling foo {"class"=>"FooJob", "at"=>"2024/04/30", "enabled"=>false, "queue"=>"default"}
11:36:07 sidekiq.1 | 2024-05-01T09:36:07.191Z pid=515927 tid=axvj WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
11:36:07 sidekiq.1 | 2024-05-01T09:36:07.191Z pid=515927 tid=axvj WARN: NoMethodError: undefined method `next_time' for nil
11:36:07 sidekiq.1 | …
```
=> undefined method `next_time' for nil:NilClass (#445)

lib/sidekiq-scheduler/scheduler.rb, lib/sidekiq-scheduler/utils.rb, spec/sidekiq-scheduler/utils_spec.rb
Hey folks!
So I recently had some free time and decided to revisit this issue I had previously fixed at the company I was working for back in 2019.
I moved the calculation method into the `Utils` module to make testing easier and added lots of comments explaining what was going on. Added tests for the method since testing this issue through Rufus is incredibly difficult.
Sorry @marcelolx for never getting back to you on this.
This would close #396 #276 and #455
=> Fix cron jobs timing

lib/sidekiq-scheduler/config.rb, lib/sidekiq-scheduler/manager.rb, lib/sidekiq-scheduler/scheduler.rb, spec/sidekiq-scheduler/config_spec.rb, spec/sidekiq-scheduler/manager_spec.rb, spec/sidekiq-scheduler/scheduler_spec.rb
ref #468 
- add `to_hash` method to `SidekiqScheduler::Manager`, `SidekiqScheduler::Scheduler` and `SidekiqScheduler::Config` classes.
- create `spec/sidekiq-scheduler/config_spec.rb` to test.
- add test in `spec/sidekiq-scheduler/scheduler_spec.rb` and `spec_sidekiq-scheduler/manager_spec.rb`.
Here is an example output of `SidekiqScheduler::Manager#to_hash`.
```ruby
{
"scheduler" => {
"scheduler_config" => {
"enabled" => true, 
"dynamic" => true, 
"dynamic_every" => "5s", 
"shedule" => {
"current" => {
"cron" => "* * * * *", 
"class" => "SomeWorker", 
"args" => "some_arg", 
"queue" => "default"
}
}, 
"listened_queues_only" => true, 
"rufus_scheduler_options" => {}
}
}
}
```
All spec are passed in my local.
Unfortunately, this doesn't affect `inspect` behavior. We need more improvement to …
=> Implement `to_hash` method in Manager, Scheduler and Config classes.

.github/workflows/ci.yml, lib/sidekiq-scheduler/extensions/web.rb, lib/sidekiq-scheduler/sidekiq_adapter.rb, web/locales/cs.yml, web/locales/de.yml, web/locales/en.yml, web/locales/es.yml, web/locales/fr.yml, web/locales/gd.yml, web/locales/it.yml, web/locales/ja.yml, web/locales/nl.yml, web/locales/pl.yml, web/locales/pt-BR.yml, web/locales/ru.yml, web/locales/sv.yml, web/locales/zh-cn.yml, web/views/recurring_jobs.erb
Sidekiq 7.3.0 and later added changes to how the web UI for plugins work.
- The registration has a first-class API to register a plugin.
- See: https://github.com/sidekiq/sidekiq/blob/main/examples/webui-ext/lib/sidekiq-redis_info/web.rb#L20
- The old registration path is still allowed, but will be removed in Sidekiq 8.0.
- New stylesheet and script helpers were added to allow linking to scripts and stylesheets for the plugin. They add nonce attributes to protect against XSS attacks.
- See: https://github.com/sidekiq/sidekiq/blob/main/examples/webui-ext/readme.md
- Sidekiq 8.0 and later will require nouce attributes for all of Sidekiq web.
To make this gem forwards compatible with 8.0...
- Added a new constant to check for Sidekiq 7.3 and later.
- For current and future Sidekiq releases, …
=> Use new web ui registration and stylesheet helpers

sidekiq-scheduler.gemspec
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
---
Hello,
even if the numbers of downloads can implicitly require MFA to publish this gem, adding this metadata will add an explicit panel on the right sidebar of the gem.
This is also in Sidekiq and a lot of popular gems (which already require MFA)
Ref: sidekiq/sidekiq#5850
=> Opt-in for MFA requirement

CHANGELOG.md, README.md, lib/sidekiq-scheduler/schedule.rb, lib/sidekiq-scheduler/scheduler.rb, lib/sidekiq-scheduler/utils.rb
```
codespell **/*.rb **/*.md -w -L shedule
```
=> Fix typos in non-production code

lib/sidekiq-scheduler/scheduler.rb, spec/sidekiq-scheduler/scheduler_spec.rb
As I described #482,  `SidekiqScheduler::Utils.calc_cron_run_time` only works with a job running periodically.
Also, `SidekiqScheduler::Utils.calc_cron_run_time` is only required jobs are execute frequently I think. So this PR changes to call it when it really needed.
Also, I added the test for `#load_schedule_job` when the cron is not periodically to prevent regression.
=> Only call SidekiqScheduler::Utils.calc_cron_run_time when it seems really necessary.

lib/sidekiq-scheduler/scheduler.rb, spec/sidekiq-scheduler/scheduler_spec.rb
The scheduled jobs have changed to instance variable by 9f90f5c.
=> Correctly clear scheduled jobs with `Scheduler#clear_schedule!`

lib/sidekiq-scheduler/redis_manager.rb
I think this method does registering, not removing.
=> Fix the doc of `SidekiqScheduler::RedisManager.register_job_instance`

lib/sidekiq-scheduler/extensions/web.rb
This PR fixes a typo in a comment.
=> Fix a typo in a method name in a comment

lib/sidekiq-scheduler/config.rb, spec/sidekiq-scheduler/config_spec.rb
Hello, is this done on purpose?
Since this is a potential breaking change, I can preserve `shedule`, and that should be deprecated and removed in 6.0
---
Potential breaking change
Ref: #470
=> [POTENTIAL BREAKING CHANGE] Fix typo in `config#to_hash`

lib/sidekiq-scheduler.rb, sidekiq-scheduler.gemspec
It seems that `tilt` is for `sinatra`.
https://github.com/sidekiq-scheduler/sidekiq-scheduler/commit/0313e5b#r14982005
I assume this was needed when the Sidekiq UI depended on `sinatra`, but that has not depended on it since
https://github.com/sidekiq/sidekiq/pull/3075.
So I think we don't need it now. Let's remove it.
=> Remove `tilt` from the dependency

web/assets/recurring_jobs/stylesheets-scheduler/recurring_jobs.css
The current dark mode does not visually differentiate between enabled and disabled jobs.  The light mode version tints disabled jobs slightly differently.  
This patch adds this in to dark mode, which signficantly reduces the cognitive load when determining which jobs are active or disabled.
Super-simple patch, simply changes the text color of disabled jobs to a light gray instead of white.
=> Adds visualization of disabled recurring jobs to Dark Mode

.github/workflows/ci.yml
This PR adds Ruby 3.4 to the CI matrix.
=> CI against Ruby 3.4

.github/workflows/ci.yml, Gemfile, lib/sidekiq-scheduler/extensions/web.rb, lib/sidekiq-scheduler/sidekiq_adapter.rb, sidekiq-scheduler.gemspec, spec/sidekiq-scheduler/scheduler_initialize_spec.rb, spec/sidekiq-scheduler/web_spec.rb, spec/support/sidekiq.rb, spec/support/store.rb, web/views/recurring_jobs.erb
Figured we may as well get the ball rolling.
This removes checks for older Sidekiq versions leaving support for only Sidekiq 7.3 which still has a level of support.
=> Clean up checks and logic for older Sidekiq versions

lib/sidekiq-scheduler/manager.rb, spec/sidekiq-scheduler/manager_spec.rb
There have been a number of issues around dynamic jobs on boot (e.g. #188, #227, #284, #125), which I think all have a common root cause.
During Manager#initialize, the schedule is loaded, even if that schedule is empty, and even in dynamic mode. See https://github.com/sidekiq-scheduler/sidekiq-scheduler/blob/9da5f130072ae8bf8f500862f44789029234b84e/lib/sidekiq-scheduler/manager.rb#L16
This causes the `schedule` key to be removed from Redis as it's now empty, so when we get to https://github.com/sidekiq-scheduler/sidekiq-scheduler/blob/9da5f130072ae8bf8f500862f44789029234b84e/lib/sidekiq-scheduler/scheduler.rb#L85, the schedule cannot be loaded as it's already gone.
This PR simply disables that initial setting of the schedule in dynamic mode.
Obviously this might affect existing running …
=> Don't clear "schedule" key on boot in dynamic schedule mode
