sidekiq-scheduler/sidekiq-scheduler

lib/sidekiq-scheduler/version.rb
@adrian-gomez could you take a look
=> Update gem version to 1.1

sidekiq-scheduler.gemspec
Remove `~> 2.12` version constraint.
=> Remove useless sidekiq version constraint

CHANGELOG.md, lib/sidekiq-scheduler/version.rb, sidekiq-scheduler.gemspec
Add web folder to the gemspec to be available by the gem.
=> Add web view to gemspec

CHANGELOG.md, lib/sidekiq-scheduler/schedule.rb, lib/sidekiq-scheduler/version.rb, lib/sidekiq-scheduler/web.rb, lib/sidekiq/scheduler.rb
Always store schedule jobs in redis to retrive them from the web
view.
=> Fixed scheduled jobs view

README.md, lib/sidekiq-scheduler.rb, lib/sidekiq-scheduler/manager.rb, lib/sidekiq/scheduler.rb, test/lib/sidekiq/scheduler_test.rb
Help to resolve https://github.com/moove-it/sidekiq-scheduler/issues/41
Needs to rewrite README
=> Add startup and enabled options

.coveralls.yml, .travis.yml, README.md, test/lib/sidekiq/scheduler_test.rb
Improve the README with different badges, fixed tests, and integrate
Travis CI and coveralls.
=> Improve documentation & fixed tests

sidekiq-scheduler.gemspec, test/test_helper.rb
Add coveralls to gemspec and test_helper.rb
=> Fixed coveralls integration

README.md
The way I read this, 'disables' should be 'enables'. Is this correct?
=> Change enabled configuration text in README

README.md, lib/sidekiq-scheduler/version.rb, sidekiq-scheduler.gemspec
Relase some small changes README updates, and add a dependency
on the gemsepec.
=> Update README and gem version

lib/sidekiq-scheduler/web.rb, lib/sidekiq/scheduler.rb, test/lib/sidekiq/scheduler_test.rb, test/lib/sidekiq/web_test.rb, web/views/recurring_jobs.erb
=> Add "Enqueue now" button

sidekiq-scheduler.gemspec
Pull request for tilt version dependency as discussed [in this ticket](https://github.com/moove-it/sidekiq-scheduler/issues/97). Thanks!
=> Drop tilt version dependency

README.md, lib/sidekiq-scheduler.rb, lib/sidekiq-scheduler/manager.rb, lib/sidekiq/scheduler.rb, spec/sidekiq-scheduler/manager_spec.rb, spec/sidekiq/scheduler_spec.rb
=> Add flag for pushing jobs on active queues only

README.md, web/locales/zh-cn.yml
1.  ``` File.expand_path ```  maybe get unexpected path;
2.  Add zh-cn locale.
=> Add zh-cn locale

lib/sidekiq/scheduler.rb
update_schedule should use a different log message than load_schedule!
=> Use precise log message when updating schedule

lib/sidekiq/scheduler.rb, spec/sidekiq/scheduler_spec.rb
See http://api.rubyonrails.org/classes/ActiveJob/Enqueuing.html#method-i-enqueue
=> Pass queue as a symbol to ActiveJob::Base#enqueue

web/locales/de.yml
Thanks so much for developing this gem. 👍 
I added a german locale file in this PR. Would be great if you'd merge it.
=> German localization

.gitignore, spec/sidekiq-scheduler/job_presenter_spec.rb, spec/sidekiq-scheduler/manager_spec.rb, spec/sidekiq-scheduler/rufus_utils_spec.rb, spec/sidekiq-scheduler/schedule_spec.rb, spec/sidekiq-scheduler/utils_spec.rb, spec/sidekiq-scheduler/web_spec.rb, spec/sidekiq/scheduler_spec.rb, spec/support/faker/schedule.rb, spec/support/store.rb
Refactored the following tests:
- job_presenter_spec
- manager_spec
- rufus_utils_spec
- schedule_spec
- utils_spec
- web_spec
=> Refactor scheduler tests

lib/sidekiq-scheduler/job_presenter.rb, lib/sidekiq/scheduler.rb, spec/sidekiq-scheduler/job_presenter_spec.rb, spec/sidekiq/scheduler_spec.rb, spec/support/store.rb, web/locales/cs.yml, web/locales/de.yml, web/locales/en.yml, web/locales/es.yml, web/locales/zh-cn.yml, web/views/recurring_jobs.erb
=> Add last execution time to jobs on the web UI

web/locales/fr.yml
=> Add french locale

lib/sidekiq-scheduler.rb, lib/sidekiq-scheduler/job_presenter.rb, lib/sidekiq-scheduler/redis_manager.rb, lib/sidekiq-scheduler/schedule.rb, lib/sidekiq/scheduler.rb, spec/sidekiq-scheduler/redis_manager_spec.rb, spec/sidekiq/scheduler_spec.rb, spec/support/store.rb
Move all the Redis requests to a separated class called RedisManager inside the SidekiqScheduler module.
=> Move all redis logic to a separate class

sidekiq-scheduler.gemspec, spec/support/initialization/redis.rb
Also:
- Stub #connection method on MockRedis instances
=> Support redis-rb v4

web/locales/nl.yml
Add translations for the Dutch language
=> Add NL locale

lib/sidekiq-scheduler/scheduler.rb
Use "each_value" instead of "each" using only value.
=> Use each_value instead of each using only value

README.md
I think y'all might have missed this while updating the readme
=> Updates rufus_scheduler_options documentation

web/locales/ja.yml
- Add Japanese to translation.
=> Add ja translations

README.md
Based on the discussion in https://github.com/moove-it/sidekiq-scheduler/issues/269.
=> README: Clarify how intervals work when Sidekiq restarts

lib/sidekiq-scheduler/version.rb
This new version includes updates to ruby version plus some
documentation updates and updates to some internals about sidekiq
=> Update version to v3.1.0

lib/sidekiq-scheduler/web.rb, spec/sidekiq-scheduler/web_spec.rb, spec/spec_helper.rb, web/views/recurring_jobs.erb
To prevent CSRF
Closes https://github.com/moove-it/sidekiq-scheduler/issues/322
=> Use POST for write web requests

lib/sidekiq-scheduler/extensions/web.rb, web/assets/stylesheets/recurring_jobs.css, web/views/recurring_jobs.erb
Based on work done on this PR https://github.com/moove-it/sidekiq-scheduler/pull/267
I just added support for the dark mode too.
Closes #267
=> Use list group instead of table for improve web UI

lib/sidekiq-scheduler/extensions/web.rb, web/views/recurring_jobs.erb
Do also not include the dark-mode functionality since it is only available on > 6
Closes #364
=> For sidekiq < 6 use styles embedded in the recurring jobs erb file

README.md
Suggesting how you can set up on Heroku and Rails to have a single scheduler thread.
=> Update README -- Suggested setup on Heroku

lib/sidekiq-scheduler/scheduler.rb, spec/sidekiq-scheduler/scheduler_spec.rb
=> Round time to ms

README.md
This PR updates the README text to reflect that v5 has been released.
=> README: refer to v5 as released

lib/sidekiq-scheduler/rufus_utils.rb, lib/sidekiq-scheduler/scheduler.rb, lib/sidekiq-scheduler/utils.rb
Noted some typos in the YARD docblocks.
Hope this helps!
=> Fix YARD docblocks

lib/sidekiq-scheduler/utils.rb, spec/sidekiq-scheduler/utils_spec.rb, spec/support/workers/address_updater_keyword.rb
Issue: https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/439
=> Issue #439 Add conditional for Hash keyword arguments

lib/sidekiq-scheduler/extensions/web.rb, web/views/recurring_jobs.erb
sidekiq-scheduler only supports Sidekiq 6.0 since #411.
=> Remove code for Sidekiq < 6.0

.github/workflows/ci.yml
Prevents introduction of breaking changes at patch or minor version level
Close #477
=> Test against all supported Ruby versions

.github/workflows/ci.yml, CHANGELOG.md, lib/sidekiq-scheduler/extensions/web.rb, lib/sidekiq-scheduler/web.rb, web/assets/recurring_jobs/stylesheets-scheduler/recurring_jobs.css
The changes in this PR make this gem compatible with Sidekiq 8
=> Sidekiq 8 Support

.github/workflows/ci.yml, Gemfile, lib/sidekiq-scheduler/sidekiq_adapter.rb, lib/sidekiq-scheduler/web.rb, sidekiq-scheduler.gemspec, spec/sidekiq-scheduler/web_spec.rb
=> Allow Sidekiq 7.3 compatability and specs. Update CI maxtrix.
